Fix previous Mingw change, which caused preprocessor issue.
Looks like a preprocessor #if is not compatible with
an include file using #pragma once.

Introduced in fd899631. Reverted in 33324b8e.
upnp.cpp(281): fatal error C1020: unexpected #endif